"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.
"""

from pathlib import Path
import os
from urllib.parse import urlparse, unquote

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-0ku_as45vs5isd^px=t#m8g#^*x7f=w#gw-xb^t@^-pom)r^t6",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [
    ".kavia.ai",
    "localhost",
    "127.0.0.1",
    "testserver",
]


# -----------------------------
# Database (PostgreSQL)
# -----------------------------
def _read_db_url_from_connection_file() -> str | None:
    """
    Attempt to read a PostgreSQL connection URL from a db_connection.txt file.

    Supported formats:
    - "postgresql://user:pass@host:port/dbname"
    - "psql postgresql://user:pass@host:port/dbname"

    NOTE:
    This is a best-effort fallback for local/dev. In production, prefer DATABASE_URL
    or POSTGRES_* env vars.
    """
    candidate_paths = [
        BASE_DIR / "db_connection.txt",
        BASE_DIR.parent / "db_connection.txt",
        # Optional: allow override for environments where DB connection file is mounted elsewhere.
        Path(os.getenv("DB_CONNECTION_FILE", "")) if os.getenv("DB_CONNECTION_FILE") else None,
    ]
    for p in candidate_paths:
        if not p:
            continue
        try:
            if p.exists():
                raw = p.read_text(encoding="utf-8").strip()
                if raw.startswith("psql "):
                    raw = raw[len("psql ") :].strip()
                if raw.startswith("postgres://"):
                    raw = raw.replace("postgres://", "postgresql://", 1)
                if raw.startswith("postgresql://"):
                    return raw
        except Exception:
            # Keep trying other paths; final fallback below.
            continue
    return None


def _parse_postgres_url(db_url: str) -> dict:
    """Parse a postgres URL and convert it into Django DATABASES['default'] structure."""
    parsed = urlparse(db_url)
    if parsed.scheme not in ("postgresql", "postgres"):
        raise ValueError(f"Unsupported DB URL scheme: {parsed.scheme}")

    user = unquote(parsed.username or "")
    password = unquote(parsed.password or "")
    host = parsed.hostname or "localhost"
    port = parsed.port or 5432
    db_name = (parsed.path or "").lstrip("/") or "postgres"

    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": db_name,
        "USER": user,
        "PASSWORD": password,
        "HOST": host,
        "PORT": str(port),
        "CONN_MAX_AGE": int(os.getenv("POSTGRES_CONN_MAX_AGE", "60")),
    }


_db_url = os.getenv("DATABASE_URL") or os.getenv("POSTGRES_URL") or os.getenv("DB_URL") or _read_db_url_from_connection_file()

if _db_url:
    DATABASES = {"default": _parse_postgres_url(_db_url)}
else:
    # Fallback: explicit environment variables
    # NOTE: request the orchestrator to set these in the container .env if DATABASE_URL is not used.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "myapp"),
            "USER": os.getenv("POSTGRES_USER", "appuser"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", "dbuser123"),
            "HOST": os.getenv("POSTGRES_HOST", "localhost"),
            "PORT": os.getenv("POSTGRES_PORT", "5001"),
            "CONN_MAX_AGE": int(os.getenv("POSTGRES_CONN_MAX_AGE", "60")),
        }
    }


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_yasg",
    "corsheaders",
    "api",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files
STATIC_URL = "static/"


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -----------------------------
# Django REST Framework
# -----------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": int(os.getenv("DRF_PAGE_SIZE", "50")),
}

# -----------------------------
# CORS / CSRF (React frontend at :3000)
# -----------------------------
_frontend_origin = os.getenv("FRONTEND_ORIGIN", "http://localhost:3000")
CORS_ALLOWED_ORIGINS = [_frontend_origin]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    _frontend_origin,
    # Allow hosted preview origins when frontend is served over https.
    os.getenv("FRONTEND_TRUSTED_HTTPS_ORIGIN", "https://localhost:3000"),
]

# Proxy / embedding settings (existing behavior)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
X_FRAME_OPTIONS = "ALLOWALL"
