# Generated by Django 5.2 on 2025-12-23 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='memorycard',
            new_name='api_memoryc_game_id_d9376d_idx',
            old_name='api_memoryc_game_id_7b90d2_idx',
        ),
    ]
